CREATE TABLE users(
	ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(28) NOT NULL,
    LAST_NAME VARCHAR(28) NOT NULL,
    EMPLOYEE_NUMBER VARCHAR(28) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);